// Per-page metadata built at build time from data — never from an LLM.
// Every page gets a canonical URL, a description, Open Graph and Twitter
// tags. Share images are generated by tools/og/make_og_images.py.
import type { Metadata } from "next";
import { absUrl, site } from "./site";

export function ogImageFor(librarySlug?: string | null): string {
  return absUrl(`/og/${librarySlug || "default"}.png`);
}

export function pageMeta({ title, description, path, librarySlug, fullTitle = false }: {
  title: string;
  description: string;
  path: string;
  librarySlug?: string | null;
  /** true when `title` already contains the site name */
  fullTitle?: boolean;
}): Metadata {
  const t = fullTitle ? title : `${title} — ${site.siteName}`;
  const url = absUrl(path);
  const image = ogImageFor(librarySlug);
  return {
    title: { absolute: t },
    description,
    alternates: { canonical: url },
    openGraph: {
      title: t, description, url, siteName: site.siteName, type: "website",
      images: [{ url: image, width: 1200, height: 630, alt: t }],
    },
    twitter: { card: "summary_large_image", title: t, description, images: [image] },
  };
}

/** Clip to a search-snippet length on a word boundary. */
export function clip(s: string, n = 158): string {
  const t = s.replace(/\s+/g, " ").trim();
  if (t.length <= n) return t;
  return t.slice(0, n - 1).replace(/\s+\S*$/, "") + "…";
}
