"""CLI for the reusable scaling tool.

Runs `backend.app.reasoning.scaling_tool.run` against our 113-paper
corpus (or any corpus you point it at via `--load`) and writes a JSON
report + a human-readable markdown table.

Free — no API calls.

Usage:
    python -m backend.app.reasoning.run_scaling_tool
    python -m backend.app.reasoning.run_scaling_tool --out data/reasoning/scaling_report.json
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO))

from backend.app.reasoning.corpus_view import load_reasoning_corpus  # noqa: E402
from backend.app.reasoning.scaling_tool import run  # noqa: E402


def _markdown(report: dict) -> str:
    """Emit the same table the hand-run study would produce, plus the
    caveats block for each curve. The bounded-yield warnings live IN the
    output, not just in a companion doc."""
    L: list[str] = []
    L.append(f"# Scaling report — {report['corpus_name']} "
             f"(N_max={report['corpus_size']}, draws={report['draws_per_N']})")
    L.append("")
    L.append("Generated by `run_scaling_tool.py`. No API calls; free.")
    L.append("")

    L.append("## Curves (mean ± SD across draws)")
    L.append("")
    header = "| N | " + " | ".join(c["scorer"] for c in report["curves"]) + " |"
    L.append(header)
    L.append("|--:" + "|--:" * len(report["curves"]) + "|")
    n_rows = len(report["curves"][0]["points"]) if report["curves"] else 0
    for i in range(n_rows):
        row_N = report["curves"][0]["points"][i]["N"]
        cells = [f"{c['points'][i]['mean']:.1f}±{c['points'][i]['sd']:.1f}"
                 for c in report["curves"]]
        L.append(f"| {row_N} | " + " | ".join(cells) + " |")
    L.append("")

    L.append("## Curve shape and caveats")
    L.append("")
    L.append("| scorer | log-log slope p | fit | caveats |")
    L.append("|:--|--:|:--|:--|")
    for c in report["curves"]:
        cav = "; ".join(c["caveats"]) if c["caveats"] else "—"
        slope = f"{c['slope_p']:.2f}" if c["slope_p"] is not None else "—"
        L.append(f"| {c['scorer']} | {slope} | {c['fit_confidence']} | {cav} |")
    L.append("")

    L.append("## Cost projection (corrected thinking-token pricing)")
    L.append("")
    L.append("| target N | extraction | embeddings | est. pairs | contra classify | **total** |")
    L.append("|--:|--:|--:|--:|--:|--:|")
    for row in report["cost_projection"]:
        L.append(f"| {row['target_N']} | ${row['extraction_usd']:.2f} | "
                 f"${row['embeddings_usd']:.4f} | "
                 f"{row['estimated_contradiction_pairs']:,} | "
                 f"${row['contradiction_classification_usd']:.2f} | "
                 f"**${row['total_usd']:.2f}** |")
    L.append("")
    if report["cost_projection"]:
        L.append(f"_{report['cost_projection'][0]['caveat']}_")
        L.append("")

    L.append("## Report-level caveats")
    L.append("")
    for c in report["report_caveats"]:
        L.append(f"- {c}")
    return "\n".join(L) + "\n"


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--out", type=Path,
                   default=REPO / "data" / "reasoning" / "scaling_report.json",
                   help="where to write the JSON report")
    p.add_argument("--md", type=Path,
                   default=REPO / "data" / "reasoning" / "scaling_report.md",
                   help="where to write the markdown table")
    args = p.parse_args()

    corpus = load_reasoning_corpus()
    print(f"loaded {len(corpus.papers)} papers")
    report = run(corpus, corpus_name="llm-calibration-113")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(report.to_dict(), indent=2))
    args.md.write_text(_markdown(report.to_dict()))

    print(f"wrote {args.out.relative_to(REPO)}")
    print(f"wrote {args.md.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
